### ISSUE TITLE
Json을 이용한 데이터 저장 클래스

### ISSUE THREAD

**Issue by orchis-seok** [ETL11-CodeCraft/HamStar#7]
- Json파일을 저장 및 읽어오는 SaveManager 클래스를 제작
- SaveManager는 싱글톤 클래스
- 각 저장 단위마다 다른 파일을 생성하도록 함

**Comment by Seobok** [comment]
https://github.com/ETL11-CodeCraft/HamStar/pull/1/commits/6cf5d17576c3f2d5a3a611b43520254abae10a9b
